#requires -Modules PSIni
[Diagnostics.CodeAnalysis.SuppressMessageAttribute( 'PSAvoidUsingWriteHost', '' )]
param()
<#
.SYNOPSIS
    Example of working with arrays in INI files using PSIni
.DESCRIPTION
    This example demonstrates how to work with arrays in INI files, including:
    - Reading and detecting array values
    - Adding to arrays
    - Removing from arrays
    - Converting arrays to scalar values
.NOTES
    Version: 2.0
    Date: May 16, 2025
    Generated by Claude 3.7 Sonnet
#>

# Set up the error action preference for cleaner output
$ErrorActionPreference = 'Stop'

# Read the sample INI file
$content = Import-Ini -Path (Join-Path $PSScriptRoot "settings.ini")

# Display information about the array type
Write-Host "== Working with Arrays in INI Files ==" -ForegroundColor Cyan

# Check if the value is an array (ArrayList)
Write-Host "The data type of key3 is: " -NoNewline
$content["arrays"]["key3"].GetType().Name
Write-Host "Array Contents:" -ForegroundColor Green
$content["arrays"]["key3"] | ForEach-Object { Write-Host "  - $_" }

# Adding a new value to the array
Write-Host "`n== Adding to an Array ==" -ForegroundColor Cyan
Write-Host "Adding 'new value' to the array..." -ForegroundColor Yellow
$content["arrays"]["key3"].Add("new value") | Out-Null
Write-Host "Array after adding a value:" -ForegroundColor Green
$content["arrays"]["key3"] | ForEach-Object { Write-Host "  - $_" }

# Removing a value from the array
Write-Host "`n== Removing from an Array ==" -ForegroundColor Cyan
Write-Host "Removing 'new value' from the array..." -ForegroundColor Yellow
$content["arrays"]["key3"].Remove("new value") | Out-Null
Write-Host "Array after removing a value:" -ForegroundColor Green
$content["arrays"]["key3"] | ForEach-Object { Write-Host "  - $_" }

# Converting an array to a scalar value
Write-Host "`n== Converting Array to Scalar ==" -ForegroundColor Cyan
Write-Host "Before conversion, key3 is an array with type: " -NoNewline -ForegroundColor Yellow
$content["arrays"]["key3"].GetType().FullName

Write-Host "Converting key3 to a scalar value 'new value'..." -ForegroundColor Yellow
$content["arrays"]["key3"] = "new value"

Write-Host "After conversion, key3 is now type: " -NoNewline -ForegroundColor Green
$content["arrays"]["key3"].GetType().FullName
Write-Host "New scalar value: $($content["arrays"]["key3"])" -ForegroundColor Green

# Saving the INI file with the updated value
$outputPath = Join-Path $PSScriptRoot "settings-array-updated.ini"
Export-Ini -InputObject $content -Path $outputPath -Force
Write-Host "`nThe updated INI file has been saved to: $outputPath" -ForegroundColor Cyan
Write-Host "Use Get-Content $outputPath to view the file contents"
