#requires -Modules PSIni
[Diagnostics.CodeAnalysis.SuppressMessageAttribute( 'PSAvoidUsingWriteHost', '' )]
param()
<#
.SYNOPSIS
    Example of removing keys from INI files using PSIni
.DESCRIPTION
    This example demonstrates how to remove keys from an INI file.
.NOTES
    Version: 2.0
    Date: May 16, 2025
    Generated by Claude 3.7 Sonnet
#>

# Set up the error action preference for cleaner output
$ErrorActionPreference = 'Stop'

# Read the INI file
$iniPath = Join-Path $PSScriptRoot "settings.ini"
$content = Import-Ini -Path $iniPath

Write-Host "== Removing Keys from INI Files ==" -ForegroundColor Cyan
Write-Host "Reading from: $iniPath" -ForegroundColor Yellow

# Display keys before removal
Write-Host "`nKeys in [arrays] section before removal:" -ForegroundColor Green
$content["arrays"].Keys | ForEach-Object { Write-Host "  - $_" }

# Remove the key
Write-Host "`nRemoving 'key4' from [arrays] section..." -ForegroundColor Yellow
$content["arrays"].Remove("key4")

# Display keys after removal
Write-Host "`nKeys in [arrays] section after removal:" -ForegroundColor Green
$content["arrays"].Keys | ForEach-Object { Write-Host "  - $_" }

# Save the modified INI file
$outputPath = Join-Path $PSScriptRoot "settings-key-removed.ini"
Export-Ini -InputObject $content -Path $outputPath -Force

Write-Host "`nThe INI file with removed key has been saved to: $outputPath" -ForegroundColor Cyan
Write-Host "Use Get-Content $outputPath to view the file contents"

# Example: How to remove an entire section
Write-Host "`n== Removing an Entire Section ==" -ForegroundColor Cyan
Write-Host "Sections before removal:" -ForegroundColor Green
$content.Keys | ForEach-Object { Write-Host "  - $_" }

Write-Host "`nRemoving [keysAndComments] section..." -ForegroundColor Yellow
$content.Remove("keysAndComments")

Write-Host "`nSections after removal:" -ForegroundColor Green
$content.Keys | ForEach-Object { Write-Host "  - $_" }

# Save the INI file with removed section
$outputPath = Join-Path $PSScriptRoot "settings-section-removed.ini"
Export-Ini -InputObject $content -Path $outputPath -Force

Write-Host "`nThe INI file with removed section has been saved to: $outputPath" -ForegroundColor Cyan

