#requires -Modules PSIni
[Diagnostics.CodeAnalysis.SuppressMessageAttribute( 'PSAvoidUsingWriteHost', '' )]
param()
<#
.SYNOPSIS
    Example of uncommmenting INI file content using PSIni
.DESCRIPTION
    This example demonstrates how to convert comments in an INI file
    back to regular key-value pairs.
.NOTES
    Version: 2.0
    Date: May 16, 2025
    Generated by Claude 3.7 Sonnet
#>

# Set up the error action preference for cleaner output
$ErrorActionPreference = 'Stop'

# Read the INI file
$iniPath = Join-Path $PSScriptRoot "settings.ini"
$content = Import-Ini -Path $iniPath

Write-Host "== Uncommenting INI File Content ==" -ForegroundColor Cyan
Write-Host "Reading from: $iniPath" -ForegroundColor Yellow

# Display the current content
Write-Host "`nCurrent content of [keysAndComments] section:" -ForegroundColor Green
$content["keysAndComments"] | Format-Table -AutoSize

# Find all comment keys in the section
$commentKeys = $content["keysAndComments"].Keys | Where-Object { $_ -like "__Comment*" }
Write-Host "`nFound $($commentKeys.Count) comment(s) in [keysAndComments] section" -ForegroundColor Yellow

# Process each comment
foreach ($commentKey in $commentKeys) {
    $commentValue = $content["keysAndComments"][$commentKey]
    Write-Host "Processing comment: $commentValue" -ForegroundColor Cyan

    # Use regex to capture the key and value from the comment
    # This pattern looks for text in format "key=value"
    if ($commentValue -match "^\s*([^=;]+)=(.*)$") {
        $key = $Matches[1].Trim()
        $value = $Matches[2].Trim()

        Write-Host "  Converting to key-value pair: [$key] = [$value]" -ForegroundColor Green

        # Add the key and value to the section
        $content["keysAndComments"][$key] = $value

        # Remove the comment
        $content["keysAndComments"].Remove($commentKey)
        Write-Host "  Removed original comment: $commentKey" -ForegroundColor DarkGray
    }
    else {
        Write-Host "  Not in key=value format, skipping: $commentValue" -ForegroundColor Yellow
    }
}

# Display the updated content
Write-Host "`nUpdated content of [keysAndComments] section:" -ForegroundColor Green
$content["keysAndComments"] | Format-Table -AutoSize

# Save the updated INI file
$outputPath = Join-Path $PSScriptRoot "settings-uncommented.ini"
Export-Ini -InputObject $content -Path $outputPath -Force

Write-Host "`nThe uncommented INI file has been saved to: $outputPath" -ForegroundColor Cyan
Write-Host "Use Get-Content $outputPath to view the file contents"
