# As of now, `shell` does not support templates.
# Once this issue is resolved, we can use the `shell` property to specify the shell for each step in the workflow.
# https://github.com/actions/runner/issues/444

name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_module:
    name: Build Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cacher
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-PSModules
      - run: ./tools/setup.ps1
        shell: pwsh
      - run: Invoke-Build -Task ShowDebugInfo
        shell: pwsh
      - run: Invoke-Build -Task Build
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: Release
          path: ./release/

  test_matrix:
    needs: build_module
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        command: ["pwsh"]
        include:
          - os: windows-latest
            command: powershell
    name: "Testing Module on: ${{ matrix.os }} with ${{ matrix.command }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Release
          path: ./release/
      - uses: actions/cache@v4
        id: cacher
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ matrix.os }}-PSModules
      - run: ./tools/setup.ps1
        shell: ${{ matrix.command }}
      - run: Invoke-Build -Task ShowDebugInfo
        shell: ${{ matrix.command }}
      - run: Invoke-Build -Task Test
        shell: ${{ matrix.command }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.command }}-Unit-Tests
          path: Test*.xml
